// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:web:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    authDomain: 'backend-baliloka.firebaseapp.com',
    storageBucket: 'backend-baliloka.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:android:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    storageBucket: 'backend-baliloka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:ios:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    storageBucket: 'backend-baliloka.appspot.com',
    iosClientId: '433877313370-ios-client-id',
    iosBundleId: 'com.example.baliLoka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:macos:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    storageBucket: 'backend-baliloka.appspot.com',
    iosClientId: '433877313370-macos-client-id',
    iosBundleId: 'com.example.baliLoka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:windows:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    storageBucket: 'backend-baliloka.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCYJhFg8oQtl-sINyii3CpZk1ZSO0_Az9s',
    appId: '1:433877313370:linux:c93584772bb67c062ff563',
    messagingSenderId: '433877313370',
    projectId: 'backend-baliloka',
    storageBucket: 'backend-baliloka.appspot.com',
  );
}
